# Copyright (c) 2023 by Microsoft.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
FROM rust:1.67 as builder

WORKDIR /usr/src/kbc

RUN apt-get update && apt-get install protobuf-compiler -y && \
    rustup component add rustfmt

COPY . .

RUN make KBC=aa_kbc && make install

FROM ubuntu:20.04

RUN apt-get update && apt install openssl -y && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/bin/attestation-agent /usr/local/bin/attestation-agent

# CMD [ "/bin/sh" ]
CMD ["attestation-agent", "--keyprovider_sock", "127.0.0.1:47777", "--getresource_sock", "127.0.0.1:48888"]

EXPOSE 47777 48888